version: '3'
services:
  app:
    build: .
    image: miska/rocnikac
    environment:
      DB_HOST: db
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: ~